name: mynotes_
description: A simple Flutter app with login, register, and note management pages.


version: 1.0.0+1


environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  emoji_picker_flutter: ^1.0.9
  image_picker: ^0.8.4+1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  google_fonts: ^3.0.1
  provider: ^6.0.0
  intl: ^0.17.0


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/sql/init.sql
    

